config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/name.rb
class Name < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :name, :due_date, :note

  validates :name, length: { maximum: 20 }

  # 判斷是否能夠刪除
  # 判斷條件可能有很多，所以將各項判斷分拆到 private method
  def can_destroy?
    # 沒過期的話，回傳 true = 可刪除
    !overdue?
  end

  # 宣告以下為 private method
  # private_method 無法被直接使用
  # `todo.overdue?` 會跳出錯誤: NoMethodError: private method `overdue?`'
  # 可以用 Ruby 原生的 Kernel#send 來呼叫 private_method: todo.send(:overdue?)
  private

  # 如果 due_date 比今天小，則回傳 true = 過期
  def overdue?
    due_date < Date.today
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, :only => [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_url
    else
      render  :action => :new
    end
  end
      
  def show
  end

  def edit
  end

  def update
    if @todo.update_attributes(todo_params)
    redirect_to todo_path(@todo)
    else
    render :action => :edit  
    end
  end

  def destroy
    if @todo.can_destroy?
      @todo.destroy
      # 跳出警告訊息，告知成功刪除
      flash[:alert] = 'List was successfully deleted !!'
      # 重新發出 request，導往列表頁。對瀏覽器來說會重整頁面
      redirect_to todos_path
    else
      # 跳出警告訊息，告知過期
      flash[:alert] = 'List is overdue, can not be deleted !!'
      # 重新發出 request，導往列表頁。對瀏覽器來說會重整頁面
      redirect_to todos_path
    end
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :due_date, :note)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>待辦事項</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<% if @todo.errors.present? %>
  <ul>
    <% @todo.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<div class="form container">
<%= form_for @todo do |f| %>
  <div class="form-group"> 
  <%= f.label :name, "Name"%>
  <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group"> 
  <%= f.label :due_date, "Due Date"%>
  <%= f.text_field :due_date, class: "form-control" %>
  </div>
  <div class="form-group"> 
  <%= f.label :note, "Note"%>
  <%= f.text_area :note, class: "form-control" %>
  </div>
  <%= f.submit %>
<% end %>
</div>

app/views/todos/edit.html.erb
<%= render :partial => "form" %>

app/views/todos/index.html.erb
<div class="container">
  <div class="page-header">
    <h2>待辦事項</h2>
  </div>

<table class="table table-striped table-condensed">
    <tr>
      <td><%= '日期' %></td>
      <td><%= '名稱' %></td>
      <td><%= '內容' %></td>

      <td><%= '編輯' %></td>
      <td><%= '刪除' %></td>
    </tr>
<% @todos.each do |todo| %>
  <tr>
    <td><%= todo.due_date %></td>
    <td><%= todo.name %></td>
    <td><%= todo.note %></td>

    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <% if todo.can_destroy? %>
      <td><%= link_to 'Destroy', todo_path(todo), method: :delete, data: { confirm: 'Delete this item ?' } %>
      <% else %>
      <td><%= '效期已過' %></td>
    <% end %>
    </td>
  </tr>
 <% end %>
</table>
<%= link_to 'New Todo', new_todo_path %>
</div>

app/views/todos/new.html.erb
<%= render :partial => "form" %>